name: smartspend
version: 1.0.0+1
description: SmartSpend - An Innovative Budget Tracker for Smarter Financial Habits
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
